name: google_mapi
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.4.0+2
  location: ^4.4.0
  geolocator: ^9.0.2
  google_api_headers: ^1.3.0
  google_maps_webservice: ^0.0.19

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

